import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

export const JUMPCLOUD_USER_MIGRATION = "20260907110000_user_jumpcloud_fields";

export const JUMPCLOUD_USER_SQL = `-- AlterTable
ALTER TABLE "User" ADD COLUMN "email" TEXT;
ALTER TABLE "User" ADD COLUMN "jumpcloudSub" TEXT;
ALTER TABLE "User" ADD COLUMN "authProvider" TEXT NOT NULL DEFAULT 'local';

-- CreateIndex
CREATE UNIQUE INDEX "User_jumpcloudSub_key" ON "User"("jumpcloudSub");
`;

export function sqliteSqlToPostgres(sql: string) {
  return sql
    .replace(/INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT/g, "SERIAL NOT NULL PRIMARY KEY")
    .replace(/DATETIME/g, "TIMESTAMP(3)")
    .replace(/\bREAL\b/g, "DOUBLE PRECISION");
}

export function postgresMigrationLock() {
  return `# Please do not edit this file manually
# It should be added in your version-control system (e.g., Git)
provider = "postgresql"
`;
}

export async function listSqliteMigrationNames(migrationsDir: string) {
  const entries = await readdir(migrationsDir, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

export async function writePostgresMigrations(options: {
  sqliteMigrationsDir: string;
  sqliteSchema?: string;
  outputDir: string;
}) {
  const names = await listSqliteMigrationNames(options.sqliteMigrationsDir);
  await mkdir(options.outputDir, { recursive: true });
  await writeFile(
    path.join(options.outputDir, "migration_lock.toml"),
    postgresMigrationLock(),
    "utf8",
  );

  for (const name of names) {
    const source = path.join(
      options.sqliteMigrationsDir,
      name,
      "migration.sql",
    );
    const sql = sqliteSqlToPostgres(await readFile(source, "utf8"));
    const destDir = path.join(options.outputDir, name);
    await mkdir(destDir, { recursive: true });
    await writeFile(path.join(destDir, "migration.sql"), sql, "utf8");
  }

  const extra: string[] = [];
  if (!options.sqliteSchema?.includes("jumpcloudSub")) {
    extra.push(JUMPCLOUD_USER_MIGRATION);
    const destDir = path.join(options.outputDir, JUMPCLOUD_USER_MIGRATION);
    await mkdir(destDir, { recursive: true });
    await writeFile(
      path.join(destDir, "migration.sql"),
      JUMPCLOUD_USER_SQL,
      "utf8",
    );
  }

  return { names: [...names, ...extra] };
}
